# FX-Commodity correlation arbitrage pair configurations

usdcad_wti:
  # Symbol definitions
  fx_symbol: "USDCAD=X"
  comd_symbol: "CL=F"  # WTI Crude Oil Futures
  comd: "WTI"  # Commodity identifier
  inverse_fx_for_quote_ccy_strength: true  # Inverse USD/CAD for CAD strength
  
  # Performance metrics
  min_trade_count: 10  # Minimum number of trades required for meaningful annualized metrics
  
  # Rolling metrics
  rolling_metrics:
    windows:
      "30D": 30
      "60D": 60
      "90D": 90
  
  # Lookback windows
  lookbacks:
    beta_window: 90      # Window for hedge ratio calculation
    z_window: 40         # Window for z-score calculation
    corr_window: 20      # Window for correlation calculation
    lookback: 252        # Lookback period for calculations
    vol_window: 20       # Volatility calculation window
  
  # Trading thresholds
  thresholds:
    entry_z: 1.0         # Relaxed Z-score threshold for entry (was 1.5)
    exit_z: 0.5          # Relaxed Z-score threshold for exit (was 0.3)
    stop_z: 3.5          # Z-score threshold for stop loss
    adf_p: 0.05          # ADF test p-value threshold
    min_abs_corr: 0.3    # Minimum absolute correlation threshold
  
  # Time stop
  time_stop:
    max_days: 10         # Maximum days to hold a position (reduced from 20)
  
  # Regime filter
  regime:
    min_abs_corr: 0.15   # Relaxed minimum absolute correlation for trading
    volatility_window: 20 # Window for volatility regime detection
    high_vol_threshold: 0.02  # High volatility threshold
    low_vol_threshold: 0.003   # Low volatility threshold
    filter_extreme_vol: true   # Filter extreme volatility regimes
    trend_window: 20      # Window for trend regime detection
    trend_threshold: 0.015 # Trend threshold
    filter_strong_trend: true  # Filter strong trending regimes
    enable_hmm: true  # Enable HMM regime filter
    hmm:
      n_states: 3
      window: 126
      df: 5.0
      tol: 1e-3
      n_iter: 100
    vix:
      thresh: 20
      boost_factor: 0.2
      max_shift: 1
  
  # Regime features (new)
  regime_features:
    volatility_regime: true
    commodity_cycle: true
    vix_overlay: true
    yield_curve_overlay: false
    vpa: true
    liquidity_sweep: true
    trend_filters: true
    correlation_features: true
  
  # Position sizing
  sizing:
    atr_window: 20        # Window for ATR calculation
    target_vol_per_leg: 0.01  # Target volatility per leg (1%)
    profit_target: 2.0    # 2x ATR for profit targets
    stop_loss: 1.5        # 1.5x ATR for stop losses
    volatility_scaling_enabled: true  # Enable volatility scaling (new)
    target_volatility: 0.01  # Target volatility (1%) (new)
    max_position_size: 0.10  # Maximum position size (10% of portfolio) (new)
    
  # Execution costs
  exec:
    default_order_type: "market"
    costs:
      small_thresh: 0.01  # Equity fraction for small trades
      large_thresh: 0.05  # Equity fraction for large trades
      small_bps: 0.5      # Basis points for small trades
      large_bps: 2.0      # Basis points for large trades
      impact_coeff: 0.5   # Quadratic impact coefficient
  
  # Risk management
  risk:
    max_position_size: 0.10  # Maximum 10% of equity per pair
    max_daily_loss: 0.02     # Maximum 2% daily loss per pair
    max_weekly_loss: 0.05    # Maximum 5% weekly loss per pair
    daily_drawdown_limit: 0.02  # Maximum 2% daily drawdown per pair
    max_trade_risk: 0.01     # Maximum 1% of portfolio per trade
    enable_circuit_breaker: true  # Enable circuit breaker for this pair
  
  # Advanced options
  use_kalman: true       # Use Kalman filter for dynamic beta
  
  # Model diversification options
  model_diversification:
    enable_ensemble: true           # Enable ensemble model
    enable_ols: true               # Enable OLS model
    enable_kalman_model: true      # Enable Kalman model
    enable_correlation_model: true # Enable correlation model
    enable_gb_model: true          # Enable Gradient Boosting model
    enable_lstm_model: true        # Enable LSTM model
    model_weights:
      ols: 0.2
      kalman: 0.2
      corr: 0.2
      gb: 0.2
      lstm: 0.2
  
  # Event calendar (optional)
  calendar:
    event_blackouts: []  # List of event types to blacklist

usdnok_brent:
  # Symbol definitions
  fx_symbol: "USDNOK=X"
  comd_symbol: "BZ=F"  # Brent Crude Oil Futures
  comd: "BRENT"  # Commodity identifier
  inverse_fx_for_quote_ccy_strength: true  # Inverse USD/NOK for NOK strength
  
  # Performance metrics
  min_trade_count: 10  # Minimum number of trades required for meaningful annualized metrics
  
  # Rolling metrics
  rolling_metrics:
    windows:
      "30D": 30
      "60D": 60
      "90D": 90
  
  # Lookback windows
  lookbacks:
    beta_window: 90      # Window for hedge ratio calculation
    z_window: 40         # Window for z-score calculation
    corr_window: 20      # Window for correlation calculation
    lookback: 252        # Lookback period for calculations
    vol_window: 20       # Volatility calculation window
  
  # Trading thresholds
  thresholds:
    entry_z: 1.0         # Relaxed Z-score threshold for entry (was 1.5)
    exit_z: 0.5          # Relaxed Z-score threshold for exit (was 0.3)
    stop_z: 3.5          # Z-score threshold for stop loss
    adf_p: 0.05          # ADF test p-value threshold
    min_abs_corr: 0.3    # Minimum absolute correlation threshold
  
  # Time stop
  time_stop:
    max_days: 10         # Maximum days to hold a position (reduced from 20)
  
  # Regime filter
  regime:
    min_abs_corr: 0.15   # Relaxed minimum absolute correlation for trading
    volatility_window: 20 # Window for volatility regime detection
    high_vol_threshold: 0.02  # High volatility threshold
    low_vol_threshold: 0.003   # Low volatility threshold
    filter_extreme_vol: true   # Filter extreme volatility regimes
    trend_window: 20      # Window for trend regime detection
    trend_threshold: 0.015 # Trend threshold
    filter_strong_trend: true  # Filter strong trending regimes
    enable_hmm: true  # Enable HMM regime filter
    hmm:
      n_states: 3
      window: 126
      df: 5.0
      tol: 1e-3
      n_iter: 100
    vix:
      thresh: 20
      boost_factor: 0.2
      max_shift: 1
  
  # Regime features (new)
  regime_features:
    volatility_regime: true
    commodity_cycle: true
    vix_overlay: true
    yield_curve_overlay: false
    vpa: true
    liquidity_sweep: true
    trend_filters: true
    correlation_features: true
  
  # Position sizing
  sizing:
    atr_window: 20        # Window for ATR calculation
    target_vol_per_leg: 0.01  # Target volatility per leg (1%)
    profit_target: 2.0    # 2x ATR for profit targets
    stop_loss: 1.5        # 1.5x ATR for stop losses
    volatility_scaling_enabled: true  # Enable volatility scaling (new)
    target_volatility: 0.01  # Target volatility (1%) (new)
    max_position_size: 0.10  # Maximum position size (10% of portfolio) (new)
  
  # Risk management
  risk:
    max_position_size: 0.10  # Maximum 10% of equity per pair
    max_daily_loss: 0.02     # Maximum 2% daily loss per pair
    max_weekly_loss: 0.05    # Maximum 5% weekly loss per pair
    daily_drawdown_limit: 0.02  # Maximum 2% daily drawdown per pair
    max_trade_risk: 0.01     # Maximum 1% of portfolio per trade
    enable_circuit_breaker: true  # Enable circuit breaker for this pair
  
  # Advanced options
  use_kalman: true       # Use Kalman filter for dynamic beta
  
  # Model diversification options
  model_diversification:
    enable_ensemble: true           # Enable ensemble model
    enable_ols: true               # Enable OLS model
    enable_kalman_model: true      # Enable Kalman model
    enable_correlation_model: true # Enable correlation model
    enable_gb_model: true          # Enable Gradient Boosting model
    enable_lstm_model: true        # Enable LSTM model
    model_weights:
      ols: 0.2
      kalman: 0.2
      corr: 0.2
      gb: 0.2
      lstm: 0.2
  
  # Event calendar (optional)
  calendar:
    event_blackouts: []  # List of event types to blacklist